// Module exports
module.exports = [
  {
    event_name: "Birthday Party",
    client_name: "John Smith",
    status: "Ongoing",
    due_date: "2024-03-15",
    location: "123 Main Street, Cityville",
    budget: 1500,
    invitees: 50,
    notes: "Please bring your own swimwear.",
    theme: "Underwater",
    special_requirements: "None",
  },
  {
    event_name: "Wedding Reception",
    client_name: "Emily Johnson",
    status: "Scheduled",
    due_date: "2024-06-20",
    location: "456 Oak Avenue, Townsville",
    budget: 3000,
    invitees: 100,
    notes: "Outdoor venue, prepare for warm weather.",
    theme: "Rustic Elegance",
    special_requirements: "Vegetarian options needed.",
  },
  {
    event_name: "Corporate Retreat",
    client_name: "David Brown",
    status: "Ongoing",
    due_date: "2024-04-30",
    location: "789 Elm Street, Villageton",
    budget: 5000,
    invitees: 30,
    notes: "Team-building activities scheduled throughout the day.",
    theme: "Business Casual",
    special_requirements: "Audio-visual equipment needed for presentations.",
  },
  {
    event_name: "Graduation Party",
    client_name: "Sarah Wilson",
    status: "Completed",
    due_date: "2024-05-10",
    location: "101 Pine Road, Hamletville",
    budget: 2000,
    invitees: 80,
    notes: "Indoor event, casual dress code.",
    theme: "Academic Achievement",
    special_requirements: "Graduation certificates to be distributed.",
  },
  {
    event_name: "Anniversary Celebration",
    client_name: "Michael Davis",
    status: "Scheduled",
    due_date: "2024-07-05",
    location: "222 Maple Avenue, Suburbia",
    budget: 2500,
    invitees: 40,
    notes: "Formal attire requested.",
    theme: "Timeless Love",
    special_requirements: "Live music performance booked.",
  },
  {
    event_name: "Baby Shower",
    client_name: "Jessica Miller",
    status: "Ongoing",
    due_date: "2024-04-25",
    location: "333 Elmwood Drive, Countryside",
    budget: 1200,
    invitees: 20,
    notes: "Gender reveal planned during the event.",
    theme: "Cute and Cozy",
    special_requirements: "Diaper cake centerpiece needed.",
  },
  {
    event_name: "Company Picnic",
    client_name: "Adam Thompson",
    status: "Scheduled",
    due_date: "2024-08-15",
    location: "444 Cedar Lane, Ruralville",
    budget: 3500,
    invitees: 150,
    notes: "Outdoor games and activities planned.",
    theme: "Fun in the Sun",
    special_requirements: "Tents and shade required for hot weather.",
  },
  {
    event_name: "Housewarming Party",
    client_name: "Amanda White",
    status: "Completed",
    due_date: "2024-02-28",
    location: "555 Oakwood Circle, Suburbia",
    budget: 800,
    invitees: 15,
    notes: "BYOB (Bring Your Own Beverage).",
    theme: "New Beginnings",
    special_requirements: "House tour requested.",
  },
  {
    event_name: "Product Launch",
    client_name: "Chris Johnson",
    status: "Ongoing",
    due_date: "2024-09-10",
    location: "666 Walnut Street, Cityville",
    budget: 6000,
    invitees: 200,
    notes: "Media coverage expected.",
    theme: "Innovation Showcase",
    special_requirements: "Product demonstration area needed.",
  },
  {
    event_name: "Holiday Party",
    client_name: "Elizabeth Martinez",
    status: "Scheduled",
    due_date: "2024-12-20",
    location: "777 Maplewood Avenue, Downtown",
    budget: 4000,
    invitees: 120,
    notes: "Gift exchange planned, please bring a wrapped gift.",
    theme: "Festive Cheer",
    special_requirements: "Santa Claus appearance scheduled.",
  },
  {
    event_name: "Charity Gala",
    client_name: "Robert Lee",
    status: "Ongoing",
    due_date: "2024-11-15",
    location: "888 Pine Street, Uptown",
    budget: 10000,
    invitees: 300,
    notes: "Black tie event, formal attire required.",
    theme: "Philanthropic Endeavors",
    special_requirements: "Silent auction items needed.",
  },
  {
    event_name: "Retirement Party",
    client_name: "Carol Taylor",
    status: "Completed",
    due_date: "2024-10-05",
    location: "999 Elmwood Avenue, Seaside",
    budget: 1500,
    invitees: 50,
    notes: "Farewell speeches planned.",
    theme: "Honoring Years of Service",
    special_requirements: "Memory book to be presented as a gift.",
  },
  {
    event_name: "Team Building Event",
    client_name: "Ryan Harris",
    status: "Scheduled",
    due_date: "2024-06-15",
    location: "123 Maple Lane, Hilltop",
    budget: 2500,
    invitees: 80,
    notes: "Team-building exercises planned throughout the day.",
    theme: "Collaboration and Communication",
    special_requirements: "Facilitator for team-building activities needed.",
  },
  {
    event_name: "Family Reunion",
    client_name: "Jennifer Garcia",
    status: "Ongoing",
    due_date: "2024-07-20",
    location: "456 Oakwood Drive, Lakeside",
    budget: 1800,
    invitees: 40,
    notes: "Potluck-style meal, please bring a dish to share.",
    theme: "Generations United",
    special_requirements: "Family photo session planned.",
  },
  {
    event_name: "Fundraising Dinner",
    client_name: "Daniel Clark",
    status: "Scheduled",
    due_date: "2024-09-25",
    location: "789 Cedar Street, Riverside",
    budget: 3000,
    invitees: 100,
    notes: "Formal fundraising event, donations appreciated.",
    theme: "Supporting a Cause",
    special_requirements: "Guest speakers scheduled.",
  },
  {
    event_name: "Art Exhibition",
    client_name: "Maria Rodriguez",
    status: "Ongoing",
    due_date: "2024-11-10",
    location: "101 Pine Lane, Art District",
    budget: 500,
    invitees: 50,
    notes: "Local artists featured, artwork available for purchase.",
    theme: "Creativity Unleashed",
    special_requirements: "Gallery space setup required.",
  },
  {
    event_name: "Book Launch",
    client_name: "James Martinez",
    status: "Completed",
    due_date: "2024-10-15",
    location: "222 Cedar Avenue, Literary District",
    budget: 1500,
    invitees: 30,
    notes: "Book signing session scheduled after the launch.",
    theme: "Literary Celebration",
    special_requirements: "Books available for purchase.",
  },
  {
    event_name: "Fashion Show",
    client_name: "Samantha Turner",
    status: "Scheduled",
    due_date: "2024-08-30",
    location: "333 Oak Lane, Fashion District",
    budget: 4000,
    invitees: 150,
    notes: "Designer collections showcased on the runway.",
    theme: "Trendsetting Glamour",
    special_requirements: "Professional models booked.",
  },
  {
    event_name: "Tech Conference",
    client_name: "Kevin Scott",
    status: "Ongoing",
    due_date: "2024-09-20",
    location: "444 Elm Street, Tech Park",
    budget: 6000,
    invitees: 200,
    notes: "Keynote speakers scheduled, breakout sessions planned.",
    theme: "Innovation and Technology",
    special_requirements: "Audio-visual equipment setup required.",
  },
  {
    event_name: "Cooking Class",
    client_name: "Laura Baker",
    status: "Scheduled",
    due_date: "2024-12-10",
    location: "555 Pine Lane, Culinary District",
    budget: 1000,
    invitees: 25,
    notes: "Hands-on cooking experience, ingredients provided.",
    theme: "Culinary Delights",
    special_requirements: "Chef instructor booked.",
  },
];
